### ISSUE TITLE
Theoretical implementation of an IF statement

### ISSUE THREAD

**Issue by Eventpicker** [ken107/databind-js#3]
Hello ken107
I am trying to implement an IF statement in your customization directories. I have tried to refactor your code and now i understand the individual steps as you proceeded. However, I have not yet managed to implement a good IF statement.

My goal is to program something like this:

JS:
`window.expr = true;`

HTML:
`<div bind-statement-if="#expr"><p>SUCCESS</p><div>`

When "expr" true then:
`<div><p>SUCCESS</p><div>`

When "expr" false then:
`<div><div>`

I am trying to implement a statement that removes the 'innerHTML' when the expression is false and adds it when it is true.
could you please help me here and send me a theoretical instruction on how to implement this? 

Would be amazing!

This implementation could be also a extension for the docs when you want it.

**Comment by ken107** [comment]
Hi Thomas,

I usually do quick-and-dirty if statements like this: `<p bind-repeater-if="#expr ? 1 : 0">SUCCESS</p>`.  Basically using a 0/1 repeater.  And I put it on the element that will be toggled on/off.

Generally you can declare custom directives through rewriting attributes, like in this example:
[examples/todolist3/mycustomdirectives.js](https://github.com/ken107/databind-js/blob/d12baacc1ea9429482d6c57f8a3128346c05c258/examples/todolist3/mycustomdirectives.js)

**Comment by Eventpicker** [comment]
uhh thats smart!
Thank you for the quick response!

Regards 
Thomas
